// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"io"
	"sync"

	"github.com/pwmorreale/rapid/data"
)

type FakeData struct {
	AddReplacementStub        func(string, string) error
	addReplacementMutex       sync.RWMutex
	addReplacementArgsForCall []struct {
		arg1 string
		arg2 string
	}
	addReplacementReturns struct {
		result1 error
	}
	addReplacementReturnsOnCall map[int]struct {
		result1 error
	}
	ExtractJSONStub        func(string, io.Reader) (string, error)
	extractJSONMutex       sync.RWMutex
	extractJSONArgsForCall []struct {
		arg1 string
		arg2 io.Reader
	}
	extractJSONReturns struct {
		result1 string
		result2 error
	}
	extractJSONReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ExtractRegexStub        func(string, io.Reader) (string, error)
	extractRegexMutex       sync.RWMutex
	extractRegexArgsForCall []struct {
		arg1 string
		arg2 io.Reader
	}
	extractRegexReturns struct {
		result1 string
		result2 error
	}
	extractRegexReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ExtractXMLStub        func(string, io.Reader) (string, error)
	extractXMLMutex       sync.RWMutex
	extractXMLArgsForCall []struct {
		arg1 string
		arg2 io.Reader
	}
	extractXMLReturns struct {
		result1 string
		result2 error
	}
	extractXMLReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	LenStub        func() int
	lenMutex       sync.RWMutex
	lenArgsForCall []struct {
	}
	lenReturns struct {
		result1 int
	}
	lenReturnsOnCall map[int]struct {
		result1 int
	}
	LookupStub        func(string) string
	lookupMutex       sync.RWMutex
	lookupArgsForCall []struct {
		arg1 string
	}
	lookupReturns struct {
		result1 string
	}
	lookupReturnsOnCall map[int]struct {
		result1 string
	}
	ReplaceStub        func(string) string
	replaceMutex       sync.RWMutex
	replaceArgsForCall []struct {
		arg1 string
	}
	replaceReturns struct {
		result1 string
	}
	replaceReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeData) AddReplacement(arg1 string, arg2 string) error {
	fake.addReplacementMutex.Lock()
	ret, specificReturn := fake.addReplacementReturnsOnCall[len(fake.addReplacementArgsForCall)]
	fake.addReplacementArgsForCall = append(fake.addReplacementArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.AddReplacementStub
	fakeReturns := fake.addReplacementReturns
	fake.recordInvocation("AddReplacement", []interface{}{arg1, arg2})
	fake.addReplacementMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeData) AddReplacementCallCount() int {
	fake.addReplacementMutex.RLock()
	defer fake.addReplacementMutex.RUnlock()
	return len(fake.addReplacementArgsForCall)
}

func (fake *FakeData) AddReplacementCalls(stub func(string, string) error) {
	fake.addReplacementMutex.Lock()
	defer fake.addReplacementMutex.Unlock()
	fake.AddReplacementStub = stub
}

func (fake *FakeData) AddReplacementArgsForCall(i int) (string, string) {
	fake.addReplacementMutex.RLock()
	defer fake.addReplacementMutex.RUnlock()
	argsForCall := fake.addReplacementArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeData) AddReplacementReturns(result1 error) {
	fake.addReplacementMutex.Lock()
	defer fake.addReplacementMutex.Unlock()
	fake.AddReplacementStub = nil
	fake.addReplacementReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeData) AddReplacementReturnsOnCall(i int, result1 error) {
	fake.addReplacementMutex.Lock()
	defer fake.addReplacementMutex.Unlock()
	fake.AddReplacementStub = nil
	if fake.addReplacementReturnsOnCall == nil {
		fake.addReplacementReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReplacementReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeData) ExtractJSON(arg1 string, arg2 io.Reader) (string, error) {
	fake.extractJSONMutex.Lock()
	ret, specificReturn := fake.extractJSONReturnsOnCall[len(fake.extractJSONArgsForCall)]
	fake.extractJSONArgsForCall = append(fake.extractJSONArgsForCall, struct {
		arg1 string
		arg2 io.Reader
	}{arg1, arg2})
	stub := fake.ExtractJSONStub
	fakeReturns := fake.extractJSONReturns
	fake.recordInvocation("ExtractJSON", []interface{}{arg1, arg2})
	fake.extractJSONMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeData) ExtractJSONCallCount() int {
	fake.extractJSONMutex.RLock()
	defer fake.extractJSONMutex.RUnlock()
	return len(fake.extractJSONArgsForCall)
}

func (fake *FakeData) ExtractJSONCalls(stub func(string, io.Reader) (string, error)) {
	fake.extractJSONMutex.Lock()
	defer fake.extractJSONMutex.Unlock()
	fake.ExtractJSONStub = stub
}

func (fake *FakeData) ExtractJSONArgsForCall(i int) (string, io.Reader) {
	fake.extractJSONMutex.RLock()
	defer fake.extractJSONMutex.RUnlock()
	argsForCall := fake.extractJSONArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeData) ExtractJSONReturns(result1 string, result2 error) {
	fake.extractJSONMutex.Lock()
	defer fake.extractJSONMutex.Unlock()
	fake.ExtractJSONStub = nil
	fake.extractJSONReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeData) ExtractJSONReturnsOnCall(i int, result1 string, result2 error) {
	fake.extractJSONMutex.Lock()
	defer fake.extractJSONMutex.Unlock()
	fake.ExtractJSONStub = nil
	if fake.extractJSONReturnsOnCall == nil {
		fake.extractJSONReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.extractJSONReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeData) ExtractRegex(arg1 string, arg2 io.Reader) (string, error) {
	fake.extractRegexMutex.Lock()
	ret, specificReturn := fake.extractRegexReturnsOnCall[len(fake.extractRegexArgsForCall)]
	fake.extractRegexArgsForCall = append(fake.extractRegexArgsForCall, struct {
		arg1 string
		arg2 io.Reader
	}{arg1, arg2})
	stub := fake.ExtractRegexStub
	fakeReturns := fake.extractRegexReturns
	fake.recordInvocation("ExtractRegex", []interface{}{arg1, arg2})
	fake.extractRegexMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeData) ExtractRegexCallCount() int {
	fake.extractRegexMutex.RLock()
	defer fake.extractRegexMutex.RUnlock()
	return len(fake.extractRegexArgsForCall)
}

func (fake *FakeData) ExtractRegexCalls(stub func(string, io.Reader) (string, error)) {
	fake.extractRegexMutex.Lock()
	defer fake.extractRegexMutex.Unlock()
	fake.ExtractRegexStub = stub
}

func (fake *FakeData) ExtractRegexArgsForCall(i int) (string, io.Reader) {
	fake.extractRegexMutex.RLock()
	defer fake.extractRegexMutex.RUnlock()
	argsForCall := fake.extractRegexArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeData) ExtractRegexReturns(result1 string, result2 error) {
	fake.extractRegexMutex.Lock()
	defer fake.extractRegexMutex.Unlock()
	fake.ExtractRegexStub = nil
	fake.extractRegexReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeData) ExtractRegexReturnsOnCall(i int, result1 string, result2 error) {
	fake.extractRegexMutex.Lock()
	defer fake.extractRegexMutex.Unlock()
	fake.ExtractRegexStub = nil
	if fake.extractRegexReturnsOnCall == nil {
		fake.extractRegexReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.extractRegexReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeData) ExtractXML(arg1 string, arg2 io.Reader) (string, error) {
	fake.extractXMLMutex.Lock()
	ret, specificReturn := fake.extractXMLReturnsOnCall[len(fake.extractXMLArgsForCall)]
	fake.extractXMLArgsForCall = append(fake.extractXMLArgsForCall, struct {
		arg1 string
		arg2 io.Reader
	}{arg1, arg2})
	stub := fake.ExtractXMLStub
	fakeReturns := fake.extractXMLReturns
	fake.recordInvocation("ExtractXML", []interface{}{arg1, arg2})
	fake.extractXMLMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeData) ExtractXMLCallCount() int {
	fake.extractXMLMutex.RLock()
	defer fake.extractXMLMutex.RUnlock()
	return len(fake.extractXMLArgsForCall)
}

func (fake *FakeData) ExtractXMLCalls(stub func(string, io.Reader) (string, error)) {
	fake.extractXMLMutex.Lock()
	defer fake.extractXMLMutex.Unlock()
	fake.ExtractXMLStub = stub
}

func (fake *FakeData) ExtractXMLArgsForCall(i int) (string, io.Reader) {
	fake.extractXMLMutex.RLock()
	defer fake.extractXMLMutex.RUnlock()
	argsForCall := fake.extractXMLArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeData) ExtractXMLReturns(result1 string, result2 error) {
	fake.extractXMLMutex.Lock()
	defer fake.extractXMLMutex.Unlock()
	fake.ExtractXMLStub = nil
	fake.extractXMLReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeData) ExtractXMLReturnsOnCall(i int, result1 string, result2 error) {
	fake.extractXMLMutex.Lock()
	defer fake.extractXMLMutex.Unlock()
	fake.ExtractXMLStub = nil
	if fake.extractXMLReturnsOnCall == nil {
		fake.extractXMLReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.extractXMLReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeData) Len() int {
	fake.lenMutex.Lock()
	ret, specificReturn := fake.lenReturnsOnCall[len(fake.lenArgsForCall)]
	fake.lenArgsForCall = append(fake.lenArgsForCall, struct {
	}{})
	stub := fake.LenStub
	fakeReturns := fake.lenReturns
	fake.recordInvocation("Len", []interface{}{})
	fake.lenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeData) LenCallCount() int {
	fake.lenMutex.RLock()
	defer fake.lenMutex.RUnlock()
	return len(fake.lenArgsForCall)
}

func (fake *FakeData) LenCalls(stub func() int) {
	fake.lenMutex.Lock()
	defer fake.lenMutex.Unlock()
	fake.LenStub = stub
}

func (fake *FakeData) LenReturns(result1 int) {
	fake.lenMutex.Lock()
	defer fake.lenMutex.Unlock()
	fake.LenStub = nil
	fake.lenReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeData) LenReturnsOnCall(i int, result1 int) {
	fake.lenMutex.Lock()
	defer fake.lenMutex.Unlock()
	fake.LenStub = nil
	if fake.lenReturnsOnCall == nil {
		fake.lenReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.lenReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeData) Lookup(arg1 string) string {
	fake.lookupMutex.Lock()
	ret, specificReturn := fake.lookupReturnsOnCall[len(fake.lookupArgsForCall)]
	fake.lookupArgsForCall = append(fake.lookupArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LookupStub
	fakeReturns := fake.lookupReturns
	fake.recordInvocation("Lookup", []interface{}{arg1})
	fake.lookupMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeData) LookupCallCount() int {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return len(fake.lookupArgsForCall)
}

func (fake *FakeData) LookupCalls(stub func(string) string) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = stub
}

func (fake *FakeData) LookupArgsForCall(i int) string {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	argsForCall := fake.lookupArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeData) LookupReturns(result1 string) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	fake.lookupReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) LookupReturnsOnCall(i int, result1 string) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	if fake.lookupReturnsOnCall == nil {
		fake.lookupReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.lookupReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) Replace(arg1 string) string {
	fake.replaceMutex.Lock()
	ret, specificReturn := fake.replaceReturnsOnCall[len(fake.replaceArgsForCall)]
	fake.replaceArgsForCall = append(fake.replaceArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ReplaceStub
	fakeReturns := fake.replaceReturns
	fake.recordInvocation("Replace", []interface{}{arg1})
	fake.replaceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeData) ReplaceCallCount() int {
	fake.replaceMutex.RLock()
	defer fake.replaceMutex.RUnlock()
	return len(fake.replaceArgsForCall)
}

func (fake *FakeData) ReplaceCalls(stub func(string) string) {
	fake.replaceMutex.Lock()
	defer fake.replaceMutex.Unlock()
	fake.ReplaceStub = stub
}

func (fake *FakeData) ReplaceArgsForCall(i int) string {
	fake.replaceMutex.RLock()
	defer fake.replaceMutex.RUnlock()
	argsForCall := fake.replaceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeData) ReplaceReturns(result1 string) {
	fake.replaceMutex.Lock()
	defer fake.replaceMutex.Unlock()
	fake.ReplaceStub = nil
	fake.replaceReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) ReplaceReturnsOnCall(i int, result1 string) {
	fake.replaceMutex.Lock()
	defer fake.replaceMutex.Unlock()
	fake.ReplaceStub = nil
	if fake.replaceReturnsOnCall == nil {
		fake.replaceReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.replaceReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addReplacementMutex.RLock()
	defer fake.addReplacementMutex.RUnlock()
	fake.extractJSONMutex.RLock()
	defer fake.extractJSONMutex.RUnlock()
	fake.extractRegexMutex.RLock()
	defer fake.extractRegexMutex.RUnlock()
	fake.extractXMLMutex.RLock()
	defer fake.extractXMLMutex.RUnlock()
	fake.lenMutex.RLock()
	defer fake.lenMutex.RUnlock()
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	fake.replaceMutex.RLock()
	defer fake.replaceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeData) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ data.Data = new(FakeData)
