// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/pwmorreale/rapid/internal/scenario"
	"github.com/spf13/viper"
)

type FakeScenario struct {
	ConfigStub        func() string
	configMutex       sync.RWMutex
	configArgsForCall []struct {
	}
	configReturns struct {
		result1 string
	}
	configReturnsOnCall map[int]struct {
		result1 string
	}
	ParseFileStub        func(string) error
	parseFileMutex       sync.RWMutex
	parseFileArgsForCall []struct {
		arg1 string
	}
	parseFileReturns struct {
		result1 error
	}
	parseFileReturnsOnCall map[int]struct {
		result1 error
	}
	ViperStub        func() *viper.Viper
	viperMutex       sync.RWMutex
	viperArgsForCall []struct {
	}
	viperReturns struct {
		result1 *viper.Viper
	}
	viperReturnsOnCall map[int]struct {
		result1 *viper.Viper
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeScenario) Config() string {
	fake.configMutex.Lock()
	ret, specificReturn := fake.configReturnsOnCall[len(fake.configArgsForCall)]
	fake.configArgsForCall = append(fake.configArgsForCall, struct {
	}{})
	stub := fake.ConfigStub
	fakeReturns := fake.configReturns
	fake.recordInvocation("Config", []interface{}{})
	fake.configMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeScenario) ConfigCallCount() int {
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	return len(fake.configArgsForCall)
}

func (fake *FakeScenario) ConfigCalls(stub func() string) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = stub
}

func (fake *FakeScenario) ConfigReturns(result1 string) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	fake.configReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeScenario) ConfigReturnsOnCall(i int, result1 string) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	if fake.configReturnsOnCall == nil {
		fake.configReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.configReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeScenario) ParseFile(arg1 string) error {
	fake.parseFileMutex.Lock()
	ret, specificReturn := fake.parseFileReturnsOnCall[len(fake.parseFileArgsForCall)]
	fake.parseFileArgsForCall = append(fake.parseFileArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ParseFileStub
	fakeReturns := fake.parseFileReturns
	fake.recordInvocation("ParseFile", []interface{}{arg1})
	fake.parseFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeScenario) ParseFileCallCount() int {
	fake.parseFileMutex.RLock()
	defer fake.parseFileMutex.RUnlock()
	return len(fake.parseFileArgsForCall)
}

func (fake *FakeScenario) ParseFileCalls(stub func(string) error) {
	fake.parseFileMutex.Lock()
	defer fake.parseFileMutex.Unlock()
	fake.ParseFileStub = stub
}

func (fake *FakeScenario) ParseFileArgsForCall(i int) string {
	fake.parseFileMutex.RLock()
	defer fake.parseFileMutex.RUnlock()
	argsForCall := fake.parseFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeScenario) ParseFileReturns(result1 error) {
	fake.parseFileMutex.Lock()
	defer fake.parseFileMutex.Unlock()
	fake.ParseFileStub = nil
	fake.parseFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScenario) ParseFileReturnsOnCall(i int, result1 error) {
	fake.parseFileMutex.Lock()
	defer fake.parseFileMutex.Unlock()
	fake.ParseFileStub = nil
	if fake.parseFileReturnsOnCall == nil {
		fake.parseFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.parseFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScenario) Viper() *viper.Viper {
	fake.viperMutex.Lock()
	ret, specificReturn := fake.viperReturnsOnCall[len(fake.viperArgsForCall)]
	fake.viperArgsForCall = append(fake.viperArgsForCall, struct {
	}{})
	stub := fake.ViperStub
	fakeReturns := fake.viperReturns
	fake.recordInvocation("Viper", []interface{}{})
	fake.viperMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeScenario) ViperCallCount() int {
	fake.viperMutex.RLock()
	defer fake.viperMutex.RUnlock()
	return len(fake.viperArgsForCall)
}

func (fake *FakeScenario) ViperCalls(stub func() *viper.Viper) {
	fake.viperMutex.Lock()
	defer fake.viperMutex.Unlock()
	fake.ViperStub = stub
}

func (fake *FakeScenario) ViperReturns(result1 *viper.Viper) {
	fake.viperMutex.Lock()
	defer fake.viperMutex.Unlock()
	fake.ViperStub = nil
	fake.viperReturns = struct {
		result1 *viper.Viper
	}{result1}
}

func (fake *FakeScenario) ViperReturnsOnCall(i int, result1 *viper.Viper) {
	fake.viperMutex.Lock()
	defer fake.viperMutex.Unlock()
	fake.ViperStub = nil
	if fake.viperReturnsOnCall == nil {
		fake.viperReturnsOnCall = make(map[int]struct {
			result1 *viper.Viper
		})
	}
	fake.viperReturnsOnCall[i] = struct {
		result1 *viper.Viper
	}{result1}
}

func (fake *FakeScenario) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	fake.parseFileMutex.RLock()
	defer fake.parseFileMutex.RUnlock()
	fake.viperMutex.RLock()
	defer fake.viperMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeScenario) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ scenario.Scenario = new(FakeScenario)
