// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"net/http"
	"sync"

	"github.com/pwmorreale/rapid/internal/config"
	"github.com/pwmorreale/rapid/internal/service"
)

type FakeService struct {
	CreateClientStub        func(*config.Request) (*http.Client, error)
	createClientMutex       sync.RWMutex
	createClientArgsForCall []struct {
		arg1 *config.Request
	}
	createClientReturns struct {
		result1 *http.Client
		result2 error
	}
	createClientReturnsOnCall map[int]struct {
		result1 *http.Client
		result2 error
	}
	CreateRequestStub        func(*config.Request) (*http.Request, error)
	createRequestMutex       sync.RWMutex
	createRequestArgsForCall []struct {
		arg1 *config.Request
	}
	createRequestReturns struct {
		result1 *http.Request
		result2 error
	}
	createRequestReturnsOnCall map[int]struct {
		result1 *http.Request
		result2 error
	}
	SendStub        func(*http.Client, *http.Request, *config.Request) (*http.Response, error)
	sendMutex       sync.RWMutex
	sendArgsForCall []struct {
		arg1 *http.Client
		arg2 *http.Request
		arg3 *config.Request
	}
	sendReturns struct {
		result1 *http.Response
		result2 error
	}
	sendReturnsOnCall map[int]struct {
		result1 *http.Response
		result2 error
	}
	ValidateResponseStub        func(*http.Client, *http.Response, *config.Request) error
	validateResponseMutex       sync.RWMutex
	validateResponseArgsForCall []struct {
		arg1 *http.Client
		arg2 *http.Response
		arg3 *config.Request
	}
	validateResponseReturns struct {
		result1 error
	}
	validateResponseReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) CreateClient(arg1 *config.Request) (*http.Client, error) {
	fake.createClientMutex.Lock()
	ret, specificReturn := fake.createClientReturnsOnCall[len(fake.createClientArgsForCall)]
	fake.createClientArgsForCall = append(fake.createClientArgsForCall, struct {
		arg1 *config.Request
	}{arg1})
	stub := fake.CreateClientStub
	fakeReturns := fake.createClientReturns
	fake.recordInvocation("CreateClient", []interface{}{arg1})
	fake.createClientMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateClientCallCount() int {
	fake.createClientMutex.RLock()
	defer fake.createClientMutex.RUnlock()
	return len(fake.createClientArgsForCall)
}

func (fake *FakeService) CreateClientCalls(stub func(*config.Request) (*http.Client, error)) {
	fake.createClientMutex.Lock()
	defer fake.createClientMutex.Unlock()
	fake.CreateClientStub = stub
}

func (fake *FakeService) CreateClientArgsForCall(i int) *config.Request {
	fake.createClientMutex.RLock()
	defer fake.createClientMutex.RUnlock()
	argsForCall := fake.createClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) CreateClientReturns(result1 *http.Client, result2 error) {
	fake.createClientMutex.Lock()
	defer fake.createClientMutex.Unlock()
	fake.CreateClientStub = nil
	fake.createClientReturns = struct {
		result1 *http.Client
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateClientReturnsOnCall(i int, result1 *http.Client, result2 error) {
	fake.createClientMutex.Lock()
	defer fake.createClientMutex.Unlock()
	fake.CreateClientStub = nil
	if fake.createClientReturnsOnCall == nil {
		fake.createClientReturnsOnCall = make(map[int]struct {
			result1 *http.Client
			result2 error
		})
	}
	fake.createClientReturnsOnCall[i] = struct {
		result1 *http.Client
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateRequest(arg1 *config.Request) (*http.Request, error) {
	fake.createRequestMutex.Lock()
	ret, specificReturn := fake.createRequestReturnsOnCall[len(fake.createRequestArgsForCall)]
	fake.createRequestArgsForCall = append(fake.createRequestArgsForCall, struct {
		arg1 *config.Request
	}{arg1})
	stub := fake.CreateRequestStub
	fakeReturns := fake.createRequestReturns
	fake.recordInvocation("CreateRequest", []interface{}{arg1})
	fake.createRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateRequestCallCount() int {
	fake.createRequestMutex.RLock()
	defer fake.createRequestMutex.RUnlock()
	return len(fake.createRequestArgsForCall)
}

func (fake *FakeService) CreateRequestCalls(stub func(*config.Request) (*http.Request, error)) {
	fake.createRequestMutex.Lock()
	defer fake.createRequestMutex.Unlock()
	fake.CreateRequestStub = stub
}

func (fake *FakeService) CreateRequestArgsForCall(i int) *config.Request {
	fake.createRequestMutex.RLock()
	defer fake.createRequestMutex.RUnlock()
	argsForCall := fake.createRequestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) CreateRequestReturns(result1 *http.Request, result2 error) {
	fake.createRequestMutex.Lock()
	defer fake.createRequestMutex.Unlock()
	fake.CreateRequestStub = nil
	fake.createRequestReturns = struct {
		result1 *http.Request
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateRequestReturnsOnCall(i int, result1 *http.Request, result2 error) {
	fake.createRequestMutex.Lock()
	defer fake.createRequestMutex.Unlock()
	fake.CreateRequestStub = nil
	if fake.createRequestReturnsOnCall == nil {
		fake.createRequestReturnsOnCall = make(map[int]struct {
			result1 *http.Request
			result2 error
		})
	}
	fake.createRequestReturnsOnCall[i] = struct {
		result1 *http.Request
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Send(arg1 *http.Client, arg2 *http.Request, arg3 *config.Request) (*http.Response, error) {
	fake.sendMutex.Lock()
	ret, specificReturn := fake.sendReturnsOnCall[len(fake.sendArgsForCall)]
	fake.sendArgsForCall = append(fake.sendArgsForCall, struct {
		arg1 *http.Client
		arg2 *http.Request
		arg3 *config.Request
	}{arg1, arg2, arg3})
	stub := fake.SendStub
	fakeReturns := fake.sendReturns
	fake.recordInvocation("Send", []interface{}{arg1, arg2, arg3})
	fake.sendMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SendCallCount() int {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	return len(fake.sendArgsForCall)
}

func (fake *FakeService) SendCalls(stub func(*http.Client, *http.Request, *config.Request) (*http.Response, error)) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = stub
}

func (fake *FakeService) SendArgsForCall(i int) (*http.Client, *http.Request, *config.Request) {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	argsForCall := fake.sendArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SendReturns(result1 *http.Response, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	fake.sendReturns = struct {
		result1 *http.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SendReturnsOnCall(i int, result1 *http.Response, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	if fake.sendReturnsOnCall == nil {
		fake.sendReturnsOnCall = make(map[int]struct {
			result1 *http.Response
			result2 error
		})
	}
	fake.sendReturnsOnCall[i] = struct {
		result1 *http.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ValidateResponse(arg1 *http.Client, arg2 *http.Response, arg3 *config.Request) error {
	fake.validateResponseMutex.Lock()
	ret, specificReturn := fake.validateResponseReturnsOnCall[len(fake.validateResponseArgsForCall)]
	fake.validateResponseArgsForCall = append(fake.validateResponseArgsForCall, struct {
		arg1 *http.Client
		arg2 *http.Response
		arg3 *config.Request
	}{arg1, arg2, arg3})
	stub := fake.ValidateResponseStub
	fakeReturns := fake.validateResponseReturns
	fake.recordInvocation("ValidateResponse", []interface{}{arg1, arg2, arg3})
	fake.validateResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateResponseCallCount() int {
	fake.validateResponseMutex.RLock()
	defer fake.validateResponseMutex.RUnlock()
	return len(fake.validateResponseArgsForCall)
}

func (fake *FakeService) ValidateResponseCalls(stub func(*http.Client, *http.Response, *config.Request) error) {
	fake.validateResponseMutex.Lock()
	defer fake.validateResponseMutex.Unlock()
	fake.ValidateResponseStub = stub
}

func (fake *FakeService) ValidateResponseArgsForCall(i int) (*http.Client, *http.Response, *config.Request) {
	fake.validateResponseMutex.RLock()
	defer fake.validateResponseMutex.RUnlock()
	argsForCall := fake.validateResponseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ValidateResponseReturns(result1 error) {
	fake.validateResponseMutex.Lock()
	defer fake.validateResponseMutex.Unlock()
	fake.ValidateResponseStub = nil
	fake.validateResponseReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateResponseReturnsOnCall(i int, result1 error) {
	fake.validateResponseMutex.Lock()
	defer fake.validateResponseMutex.Unlock()
	fake.ValidateResponseStub = nil
	if fake.validateResponseReturnsOnCall == nil {
		fake.validateResponseReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateResponseReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createClientMutex.RLock()
	defer fake.createClientMutex.RUnlock()
	fake.createRequestMutex.RLock()
	defer fake.createRequestMutex.RUnlock()
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	fake.validateResponseMutex.RLock()
	defer fake.validateResponseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Service = new(FakeService)
