name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

    - name: StaticCheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
           make staticcheck    

    - name: Lint
      run: make lint

    - name: Tests
      run: make test
