name: Tests & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'

    - name: Install Dependencies
      run: |
        go get ./...
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/mgechev/revive@latest

    - name: Build
      run: make

    - name: Run staticcheck
      run: make staticcheck    

    - name: Lint
      run: make lint

    - name: Tests
      run: make test
