name: Tests & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Cache Go tools
      uses: actions/cache@v4
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-go-tools-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-tools-

    - name: Install Tools
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/mgechev/revive@latest

    - name: Build
      run: make

    - name: Run staticcheck
      run: make staticcheck

    - name: Lint
      run: make lint

    - name: Tests
      run: make test

    - name: Race Detector
      run: make race

    - name: Coverage
      run: go test -coverprofile=coverage.out ./...

    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.out
